"""Incoming-mail ringtones: the seven tones the user's Get It app plays.

The WAVs under assets/ringtones/ are generated by scripts/make_ringtones.py from
Get It's own synthesis recipes (they are the user's tones, not a stock set) and
are played looped: the ring stops when the message is read, or from the tray.

Playback is QtMultimedia's QSoundEffect, which rides the PyQt5 GUI extra.
winsound covers a Qt build without the multimedia plugins, and with neither the
ring is a no-op — a box with no audio device must never break the GUI.
"""

import contextlib

from ..config import RESOURCE_ROOT

try:
    from PyQt5.QtCore import QUrl
    from PyQt5.QtMultimedia import QSoundEffect
except Exception:  # pragma: no cover - a Qt build without QtMultimedia
    QUrl = None
    QSoundEffect = None

# Dropdown order and labels; the ids are the asset file names.
TONES: list[tuple[str, str]] = [
    ("dingdong", "叮咚"),
    ("chime", "风铃"),
    ("beep", "蜂鸣"),
    ("alert", "警示"),
    ("notification", "通知"),
    ("piano", "钢琴"),
    ("synth", "合成器"),
]

TONE_IDS = [tone_id for tone_id, _ in TONES]

TONE_LABELS = dict(TONES)

# Fallback for an unknown id in config.json and for a missing asset — keep in
# step with Config.ring_tone.
DEFAULT_TONE = TONE_IDS[0]

# QSoundEffect.Infinite, or a harmless 1 when QtMultimedia is not importable
# (the effect is never built then, so the value is never used).
LOOP_FOREVER = QSoundEffect.Infinite if QSoundEffect is not None else 1


def tone_path(tone: str) -> str | None:
    """Bundled WAV for one tone id, or None when the asset is not there."""
    if tone not in TONE_LABELS:
        return None
    path = RESOURCE_ROOT / "assets" / "ringtones" / f"{tone}.wav"
    return str(path) if path.is_file() else None


class Ringer:
    """Loops one ringtone until stopped; silent when no backend exists."""

    def __init__(self) -> None:
        self._effect = None  # QSoundEffect, built on first use
        self._qt_broken = False
        self._tone: str | None = None  # the looping tone; None = not ringing
        self._playing = False  # a backend was started (loop or preview)

    @property
    def ringing(self) -> bool:
        """True while a tone is playing (what the tray flash follows)."""
        return self._tone is not None

    def start(self, tone: str) -> None:
        """Ring `tone` in a loop (same tone already ringing: leave it be)."""
        path = tone_path(tone) or tone_path(DEFAULT_TONE)
        if path is None:  # assets missing entirely (a bare checkout)
            return
        if tone == self._tone:
            return
        self.stop()
        if self._play_qt(path, loops=LOOP_FOREVER) or self._play_winsound(path, loop=True):
            self._tone, self._playing = tone, True

    def preview(self, tone: str) -> None:
        """Play `tone` once: the settings page's audition (no loop)."""
        path = tone_path(tone) or tone_path(DEFAULT_TONE)
        if path is None:
            return
        self.stop()
        if self._play_qt(path, loops=1) or self._play_winsound(path, loop=False):
            self._playing = True

    def stop(self) -> None:
        """Silence whatever is playing.

        A no-op when nothing is: the GUI calls this every second while there is
        no unread mail, and it must not poke the audio device that often.
        """
        if not self._playing:
            return
        self._playing, self._tone = False, None
        if self._effect is not None:
            with contextlib.suppress(Exception):
                self._effect.stop()
        with contextlib.suppress(Exception):
            import winsound  # noqa: PLC0415 (Windows only, and only to silence one)

            winsound.PlaySound(None, winsound.SND_PURGE)

    # ── backends ──

    def _play_qt(self, path: str, loops: int) -> bool:
        effect = self._ensure_effect()
        if effect is None:
            return False
        try:
            effect.setSource(QUrl.fromLocalFile(path))
            effect.setLoopCount(loops)
            effect.setVolume(0.9)
            effect.play()
        except Exception:
            self._qt_broken = True
            return False
        return True

    def _ensure_effect(self):
        """The QSoundEffect, built once; None when Qt cannot play at all."""
        if self._effect is None and not self._qt_broken:
            try:
                self._effect = QSoundEffect()
            except Exception:  # no QtMultimedia in this build
                self._qt_broken = True
        return self._effect

    @staticmethod
    def _play_winsound(path: str, loop: bool) -> bool:
        try:
            import winsound  # noqa: PLC0415
        except Exception:
            return False
        flags = winsound.SND_FILENAME | winsound.SND_ASYNC | (winsound.SND_LOOP if loop else 0)
        try:
            winsound.PlaySound(path, flags)
        except Exception:
            return False
        return True
