"""Incoming-mail ringtones: the seven tones the user's Get It app plays.

The WAVs under assets/ringtones/ are generated by scripts/make_ringtones.py from
Get It's own synthesis recipes (they are the user's tones, not a stock set) and
are played **once**, in full (2026-09-11 user instruction: 「铃声只响一次，但是
图标保持闪动」). The unread state rides the tray icon, not the tone: the flash
keeps going until the friend view marks the thread read, and the tray's
「停止铃声」 only cuts a tone that is still sounding.

Playback is QtMultimedia's QSoundEffect, which rides the PyQt5 GUI extra.
winsound covers a Qt build without the multimedia plugins, and with neither the
ring is a no-op — a box with no audio device must never break the GUI.
"""

import contextlib

from ..config import RESOURCE_ROOT

try:
    from PyQt5.QtCore import QUrl
    from PyQt5.QtMultimedia import QSoundEffect
except Exception:  # pragma: no cover - a Qt build without QtMultimedia
    QUrl = None
    QSoundEffect = None

# Dropdown order and labels; the ids are the asset file names.
TONES: list[tuple[str, str]] = [
    ("dingdong", "叮咚"),
    ("chime", "风铃"),
    ("beep", "蜂鸣"),
    ("alert", "警示"),
    ("notification", "通知"),
    ("piano", "钢琴"),
    ("synth", "合成器"),
]

TONE_IDS = [tone_id for tone_id, _ in TONES]

TONE_LABELS = dict(TONES)

# Fallback for an unknown id in config.json and for a missing asset — keep in
# step with Config.ring_tone.
DEFAULT_TONE = TONE_IDS[0]


def tone_path(tone: str) -> str | None:
    """Bundled WAV for one tone id, or None when the asset is not there."""
    if tone not in TONE_LABELS:
        return None
    path = RESOURCE_ROOT / "assets" / "ringtones" / f"{tone}.wav"
    return str(path) if path.is_file() else None


class Ringer:
    """Plays one ringtone once; silent when no backend exists."""

    def __init__(self) -> None:
        self._effect = None  # QSoundEffect, built on first use
        self._qt_broken = False
        self._tone: str | None = None  # the tone this ring is armed with; None = none
        self._playing = False  # a backend was started (a ring or an audition)

    @property
    def ringing(self) -> bool:
        """True from the moment a tone is started until `stop()`.

        Not "sound is audible right now": the tone is one-shot, and the GUI asks
        this every second — if it went False when the WAV ended, the unread poll
        would re-play the same tone on every tick.
        """
        return self._tone is not None

    def start(self, tone: str) -> None:
        """Ring `tone` once (same tone already ringing: leave it be)."""
        path = tone_path(tone) or tone_path(DEFAULT_TONE)
        if path is None:  # assets missing entirely (a bare checkout)
            return
        if tone == self._tone:
            return
        self.stop()
        if self._play_qt(path) or self._play_winsound(path):
            self._tone, self._playing = tone, True

    def preview(self, tone: str) -> None:
        """Play `tone` once for the settings page's audition.

        Same one-shot playback as a real ring; `_tone` stays None, so an
        audition never arms the ring (nor lights the tray's 停止铃声).
        """
        path = tone_path(tone) or tone_path(DEFAULT_TONE)
        if path is None:
            return
        self.stop()
        if self._play_qt(path) or self._play_winsound(path):
            self._playing = True

    def stop(self) -> None:
        """Silence whatever is playing, and disarm the ring.

        A no-op when nothing is: the GUI calls this every second while there is
        no unread mail, and it must not poke the audio device that often. Since
        a tone is one-shot, this usually just clears the armed flag — the tray's
        「停止铃声」 is for a ring that is still sounding.
        """
        if not self._playing:
            return
        self._playing, self._tone = False, None
        if self._effect is not None:
            with contextlib.suppress(Exception):
                self._effect.stop()
        with contextlib.suppress(Exception):
            import winsound  # noqa: PLC0415 (Windows only, and only to silence one)

            winsound.PlaySound(None, winsound.SND_PURGE)

    # ── backends ──

    def _play_qt(self, path: str) -> bool:
        effect = self._ensure_effect()
        if effect is None:
            return False
        try:
            effect.setSource(QUrl.fromLocalFile(path))
            effect.setLoopCount(1)
            effect.setVolume(0.9)
            effect.play()
        except Exception:
            self._qt_broken = True
            return False
        return True

    def _ensure_effect(self):
        """The QSoundEffect, built once; None when Qt cannot play at all."""
        if self._effect is None and not self._qt_broken:
            try:
                self._effect = QSoundEffect()
            except Exception:  # no QtMultimedia in this build
                self._qt_broken = True
        return self._effect

    @staticmethod
    def _play_winsound(path: str) -> bool:
        try:
            import winsound  # noqa: PLC0415
        except Exception:
            return False
        # No SND_LOOP: one play, matching the Qt backend's loop count of 1.
        flags = winsound.SND_FILENAME | winsound.SND_ASYNC
        try:
            winsound.PlaySound(path, flags)
        except Exception:
            return False
        return True
